### ISSUE TITLE
QrCode::encoding('SHIFT-JIS') 

### ISSUE THREAD

**Issue by mosvict** [SimpleSoftwareIO/simple-qrcode#155] opened 2020-05-26 17:59 UTC
Hello. 
I need to build qrcode with shift-jis.
So I have checked documentation and implemented with shift-jis.
But I can see encoding error. How to solve it?
[https://prnt.sc/so9e5k](url)
[https://prnt.sc/so9ehq](url)

**Comment by SimplyCorey** [comment] 2020-05-26 18:03
Can you provide your method call please?

**Comment by mosvict** [comment] 2020-05-26 18:05
$var="ありがとうございます。";
<img src="data:image/png;base64, {{ base64_encode(QrCode::encoding('SHIFT-JIS')->format('png')->size(400)->errorCorrection('H')->generate($var)) }}">

**Comment by mosvict** [comment] 2020-05-26 18:09
`
$var = mb_convert_encoding($var, "SJIS", "UTF-8");
`
I tried to convert string to SJIS from UTF-8. But It was failed too.
Please help me.  :)

**Comment by SimplyCorey** [comment] 2020-05-26 18:12
I think the issue is your calling format *after* you set the encoding.  This is a known design flaw in 2.x and is resolved in the new 3.x release coming this week :)

Try this:

```
$var="ありがとうございます。"; <img src="data:image/png;base64, {{ base64_encode(QrCode::format('png')->encoding('SHIFT-JIS')->size(400)->errorCorrection('H')->generate($var)) }}">
```

**Comment by mosvict** [comment] 2020-05-26 18:15
Thanks. I tried but I see same error.
[https://prnt.sc/so9p4t](url)

**Comment by SimplyCorey** [comment] 2020-05-26 18:17
Would UTF-8 work for you?

`QrCode::format('png')->encoding('UTC-8')->size(400)->errorCorrection('H')->generate($var))`

**Comment by mosvict** [comment] 2020-05-26 18:18
Sure. UTF-8 is working well.

**Comment by SimplyCorey** [comment] 2020-05-26 18:20
Awesome 👍 

There must be a bug in 2.x with this.  I just tried the exact code in 3.x and it works.  This should release on Thursday if you want to upgrade then.

**Comment by SimplyCorey** [comment] 2020-05-26 18:20
From 3:

![image](https://user-images.githubusercontent.com/624784/82936101-136dec00-9f5c-11ea-99a1-70269a7c9e6c.png)

**Closed by SimplyCorey** 2020-05-26 18:20 UTC

**Comment by mosvict** [comment] 2020-05-26 18:21
Thanks. Thusday? 
Actually, It is urgent for me. :(

**Comment by SimplyCorey** [comment] 2020-05-26 18:27
You can use the UTF-8 encoding on 2.x until then.
