### ISSUE TITLE
Possible to remove half dots

### ISSUE THREAD

**Issue by gitleif** [SimpleSoftwareIO/simple-qrcode#242] opened 2021-12-07 18:48 UTC
Behind the merged center image there should be possible to completly remove the dots that are not completely visible. See attached image.
![suggestion](https://user-images.githubusercontent.com/26165143/145088293-82e22b90-0c30-446f-9ef8-00f641b4b503.png)

**Comment by SimplyCorey** [comment] 2021-12-09 18:27
Not currently, but I'd accept a PR that could better center the image.

**Comment by SimplyCorey** [comment] 2021-12-14 18:59
Closing as a duplicate of https://github.com/SimpleSoftwareIO/simple-qrcode/issues/192

**Closed as completed by SimplyCorey** 2021-12-14 18:59 UTC
