### ISSUE TITLE
Transparency?

### ISSUE THREAD

**Issue by squaddie** [SimpleSoftwareIO/simple-qrcode#136] opened 2019-08-31 18:55 UTC
Hi, so can I set transparent background in a latest version? I can't find any method, to do this. Also backgroundColor accept rgb, not rgba,  so it's impossible?

**Comment by SimplyCorey** [comment] 2020-02-04 12:44
This is a feature request and a duplicate of #38

**Closed by SimplyCorey** 2020-02-04 12:44 UTC
